name: main
on:
  push:
    branches: [main]
    tags: v*
  pull_request:
    branches: [main]
env:
  RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: make
      - run: git diff --exit-code
      - if: failure()
        run: docker-compose logs
      - run: make down
