name: main
on:
  push:
    branches: [main]
    tags: v*
  pull_request:
    branches: [main]
env:
  RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
jobs:
  main:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12.x'
      - run: yarn install
      - run: make
      - run: git diff --exit-code
      - if: failure()
        run: docker-compose logs
      - run: make down
      # - if: startsWith(github.ref, 'refs/tags')
      #   run: npm publish
      # - if: startsWith(github.ref, 'refs/heads')
      #   run: npm publish --dry-run
      - run: npm publish
